djangocon/2023.djangocon.us

.gitignore
.tool-versions
Gemfile
Gemfile.lock
README.md

This PR makes a few changes to support issues I ran into getting setup:
- Ignores `node_modules`
- Explicitly sets versions for supporting tech in `.tool-version` (supported by asdf-vm)
- Adds Rake & HTML Proofer as dependencies
- Updates the README to explicitly call out prereqs and their versions and moves supporting info into relevant sections
I am not a Ruby nor Jekyll user so perhaps this patch isn't 100% accurate and maybe we left those deps out on purpose 😅

Update instructions and deps for getting started

---

_pages/venue.html

This removes the old commented out iframe. I wasn't sure if we wanted to use the API approach again, but this is the embedded content Google maps is pushing us to use.

Enable venue header with iframe Google maps view.

---

_layouts/new_layout.html
_pages/speaking-resources.md
_pages/speaking.md

I created a new layout for speaking and resources page. 
1. Basically I created a new HTML file and copied the code of homepage-coming-soon.html and pasted it into the new file
2. I added header tag gotten from default.html
3. Also added {{ content }} element gotten from default.html. It uses its former style (styling in base.html).
4. I commented the (list-style for ul and li) and added list-style-position styling.

re-work the content of speaking and resources page to a similar template as homepage-coming-soon by creating a new layout

---

_pages/speaking.md

I've had two 2022 attendees miss the fact that we have online talks, so maybe breaking this out into a separate sub-heading might draw more attention to it.

✏️ Make the fact that we have online talks more prominent

---

_pages/covid19.html

I removed the references to ShareMy.health in case we don't use them for the test verification process.

Update the covid19 page with 2023's policy.

---

_pages/homepage-coming-soon.html

Link pointed to 2021 talks instead of 2022

Update last year talks link

---

_pages/about.html

Also bring back the pre-conference schedule block
Addresses #76
Screenshot with the old theme:

🔧 Fix dates for 2023 on about page

---

_layouts/home.html

1. Drops the conference schedule bit from the 3 cards under "A Conference with Heart". For now I'm just going with 2 columns mainly because I can't find what we used as a third card before the schedule was launched.
2. Adds buttons to buy tickets and submit a talk to the hero
Addresses #76

🔧 More home layout fixes

---

_layouts/home.html

Addresses the issue where people have a navigable link to pages that have 2022 content.

Disable links to talks, sprints, tutorials.

---

_pages/speaking-resources.md

1. Add notes about accessibility
2. Refactor slide guidelines to be separate from talk guidelines
3. Remove some notes about which software to use
4. Add the ability to submit talk slides in advance
5. Give some quick tips for hooking your laptop up to the projector
Fixes #6.
Screenshots:

✏️ Improve the speaking resources page for post-CFP stuff

---

.github/workflows/deploy_hooks.yml

This requires a new repository secret SLACK_COMMUNICATIONS_WEBHOOK_URL which is generated via a Slack app.

When a blog PR is deployed, notify the communications channel.

---

.github/workflows/deploy_hooks.yml

Slack wants a payload with a text property.
This also supports actually running the workflow on demand by skipping the check if the event is a deployment_status update.

Send the proper webhook payload to Slack.

---

pull_request_template.md

This PR template serves as a guide and reminder for contributors to ensure that the "blog" label is applied when creating blogs so that it's published to Slack.
Hi @tim-schilling , thoughts on this?

#125 Create PR template to apply blog label

---

_pages/schedule.html

Suggested by @emullaney: mark the tutorials as being online in the header on the schedule page

✏️ Mark on the schedule page that tutorials are online

---

_layouts/base.html
_pages/iframe.html
static/iframe_compat.js
static/main.css

LoudSwarm wants to have links to various types of content that exists on our site already. Rather than duplicating and dealing with stale data, this allows our site to be more easily used in an iframe.
This relies on JavaScript to detect that we're in an iframe, then remove the bulky nav and footer elements. This means that if a user has JavaScript disabled (they're going to have a tough time on LoudSwarm) they would still see the header and footer. Additionally, if they are using a slower machine, the header and footer would remain visible for a noticeable amount of time. But again, they're probably going to have a bad time on the LoudSwarm platform.

Support rendering pages without the nav and footer for iframes.

---

_layouts/session-details.html

Spotted while working on accessibility fixes – sessions weren’t using the correct time zone in those time zone links.

Fix incorrect time zone in session time link

---

_includes/footer.html
_layouts/new_layout.html
_layouts/post-list.html
_layouts/post.html
_pages/homepage-coming-soon.html
_pages/tickets.html
_pages/venue.html

Related: #196. Fixes a number of occurrences of HTML markup causing validation errors or warnings. Each commit is for a fully separate issue.
- [Fix invalid table markup](https://github.com/djangocon/2023.djangocon.us/commit/aa9f5503e7625cd7018cd6f1d367bd73d750ea66) – just an extra `<tr>`.
- [Fix duplicate id on venue page](https://github.com/djangocon/2023.djangocon.us/commit/9ecc192dc761e80a75ffe33507596ab382837c6c) – two `#hotel` sections.
- [Add valid datetime attributes to time elements](https://github.com/djangocon/2023.djangocon.us/commit/64d751d5b8025c206ecb6423dd3b770e6c9c9c08) – the `<time>` element will only serve its purpose if its contents are either formatted in one of its supported formats, or if the `datetime` attribute does so.
- [Remove unnecessary footer …

Fix invalid HTML markup

---

_config.yml
_pages/venue.html

Marks the room block as closed on the venue page and changes the hotel link to point to the hotel's main page

🏨 Update the hotel page to indicate that the room block is closed

---

_schedule/talks/2023-10-17-17-15-t0-an-approach-to-lightweight-tenancy-management-using-django-rest-framework.md

Updated talk description to consistently use `API` (not `api`) and `multitenancy` (not `multi-tenancy`)

Update Eliana Rosselli's talk description to use consistent terminology

---

_presenters/calvin-hendryx-parker.md
_schedule/talks/2023-10-16-10-30-t0-sponsored-talk-six-feet-up.md

1. Updates Calvin's bio with new copy from Laura
2. Adds the Six Feet Up sponsored talk to Monday after the keynote
Screenshot:

Add the Six Feet Up sponsored talk

---

bin/process.py
shots.yml

If a speaker isn't referenced in any talks, don't regenerate their opengraph images. This should help with creating images for speakers with no talk titles.

🔧 Skip unused talks in shot generation

---

_schedule/talks/2023-10-18-t0-sponsored-talk-platform-sh.md

Adds the platform.sh sponsored talk to our schedule

📆 Add the sponsored talk from Platform.sh to the schedule

---

_presenters/dawn-wages.md
_schedule/talks/2023-10-18-10-30-t0-sponsored-talk-platform-sh.md

Just fixes the speaker image URL for Guillaume's talk

🔧 Fix the speaker image for the Platform.sh sponsored talk

---

_includes/nav.html
_layouts/home.html
_layouts/session-details.html
_pages/covid19.html
_pages/faqs.html
_pages/schedule.html
_pages/tickets.html
_pages/tutorials.html

Pages affected:
- Home page
- Top nav
- Schedule page
- Ticket page
- Tutorials schedule page
Switches the HTML comments to template contents so the links aren't visible in the HTML.

🔧 Hide the "buy tickets" links since tickets are no longer on sale

---

_pages/covid19.html

October 13 is (was) a Friday, not a Thursday. While this was in the past and
is now unlikely to cause any problems with when people took a test, it's good to
have the correct information. Especially if someone is going to use this page as
the basis for 2024, it will make it easier for them to update.

Update date in COVID-19 policy

---

_includes/youtube-copy-and-paste.html
_pages/speaking-youtube-checklists.md

This updated our YouTube Checklist / Clipboard pages for 2023. 
I tried to get the Mastodon links to work but Jekyll assumes any content that starts with `@` should be formatted as a GitHub profile link and I couldn't figure it out. 🤷

:hammer: Updates youtube templates for 2023
