_pages/homepage-coming-soon.html
_pages/homepage-default.md

Swap out the homepage with our coming soon page. 
Related to https://github.com/djangocon/djangocon.us/pull/2

:tractor: :pencil: Prep for 2023

---

_includes/nav.html

Hide the schedule and venue tabs by placing comments these tabs in the nav.html file

chore:hide schedule, venue tabs

---

_pages/venue.html

Just a quick note about the Duke football game

✏️Add note to venue page about Duke football

---

_organizers/michael-clark.md

Add Michael Clark organizer info & photo

Add Michael Clark info and photo

---

.all-contributorsrc
README.md

I added a plugin in the hopes of automating this. 
Here is how to do this by hand: 
```shell
npx all-contributors-cli generate
```

:busts_in_silhouette: Updates contributors

---

.github/CODEOWNERS
.github/settings.yml

Emmanuel has volunteered as website co-chair

🔧 Add @emmakodes as a code owner

---

_pages/opportunity-grants.md

Cheers to @wsvincent for pointing this out.

🔧 Fix duplicate lines in the OG main page

---

.github/CODEOWNERS
.github/settings.yml

Just in case the bot wrecked his permissions

🔧 Make @tim-schilling an admin

---

EDITORS_GUIDE.md
_includes/styleguide/styleguide-branding.html
_includes/styleguide/styleguide-logos.html
_pages/homepage-coming-soon.html
_pages/homepage-recap.html
package.json

Also fixes a link to our github repo that was referencing a non-existent develop branch.

Update more year references to 2023

---

_pages/speaking.md

We mention the $500 travel reimbursement lower on the page but the top said we didn't have it! Fixing that and removing a todo note.

Clarify benefits of speaking and remove todo note

---

_pages/conduct.html

+ Adrienne, Peter, Tim S
- Lacey, Logan, Jorge
Addresses #76

✏️ Update CoC team for 2023

---

_pages/faqs.html

- Sponsorships and ticket sales are open
- We have speaker mentors
- We have Q&A time
- We have after-hours events
- Lactation room blog post is not yet ready
Addresses #76

✏️ Update FAQs for 2023

---

_pages/sponsors-information.md

Per Catherine and Dawn, nobody has claimed this yet, so we can remove the strikethrough.
Addresses #76

✏️ Mark the lanyard sponsorship as unclaimed

---

_layouts/home.html
_pages/homepage-coming-soon.html
_pages/homepage-default.md
_src/scss/_settings.scss
_src/scss/layout/_navbar.scss
static/main.css

Please wait until @mtrythall is ready in the #website-design channel on Slack before merging.

:tractor: Swaps splash page and default home page

---

README copy.md
_data/photos.yml
_includes/styleguide/styleguide-introduction.html
_includes/titlebar.html
_pages/homepage-recap.html
_pages/invite-letter.html
_pages/speaking-resources.md
_posts/2023-04-19-end-of-covid-19-emergency-declaration.md
_posts/2023-05-08-benefits-of-speaking-djangocon.md
_src/scss/main.scss

I _think_ I got them all anyway.

🚜 Fix all references to DjangoCon that didn't explicitly mention DCUS

---

_layouts/home.html
_pages/opportunity-grants.md
_pages/speaking.md

Also bring back signing up for the mailing list
Do not merge before 6 PM EDT on 2023-05-15

🔧 Mark the CFP and OG windows as being closed

---

_pages/faqs.html

- Refunds are still available
- Tutorial swaps are still open

🔧 Update FAQs related to tickets

---

.github/workflows/deploy_hooks.yml

Fix syntax error with deployment webhook flow.

---

bin/process.py

Pydantic just released v2. This PR addresses those recent changes. Please note this will reformat most of our collections, which can be done in a followup PR. 
This needs more testing. I focused on the warnings from `python bin/process.py fmt|validate`, which should cover >90% of its usage.

:arrow_up: Updates pydantic usage to v2

---

_presenters/calvin-hendryx-parker.md
_presenters/charlotte-mays.md
_presenters/cheuk-ting-ho.md
_presenters/chris-may.md
_presenters/dawn-wages.md
_presenters/deb-nicholson.md
_presenters/denny-biasiolli.md
_presenters/james-walters.md
_presenters/josh-thomas.md
_presenters/marc-gibbons.md
_presenters/mario-munoz.md
_presenters/meagen-voss.md
_presenters/paolo-melchiorre.md
_presenters/paul-gilzow.md
_presenters/philip-james.md
_presenters/ramon-huidobro.md
_presenters/ryan-cheley.md
_presenters/sage-abdullah.md
_presenters/sheena.md
_presenters/tobias-mcnulty.md
bin/process.py

Fixes #134 by migrating existing Mastodon handles as needed.

:tractor: Adds migrate_mastodon_handle

---

_posts/2023-07-10-announcing-lineup.md

1. Add social media links
2. Add speakers brought in from the wait list

✏️ Update talk list

---

_schedule/talks/2023-10-17-14-55-t0-nothing-for-us-without-us-breaking-unconscious-bias-in-building-products.md

Victor emailed me asking to replace his talk description with his abstract. This takes care of that.

Replace Victor's talk description with his abstract

---

_schedule/talks/2023-10-17-11-10-t0-postgres-performance-from-slow-to-pro.md

Adding a bit more text to the Postgres performance talk listing.

Adding more to Postgres Performance Slow to Pro Talk Listing

---

_presenters/victor-ogunjobi.md

Drop Victor's pronouns

---

_presenters/stephen-mitchell.md

Remove Stephen's pronouns

---

_posts/2023-07-21-announcing-schedule.md

Fix link to fosstodon.org

---

_sponsors/2021-10-04-psf.md

Reverts djangocon/2023.djangocon.us#96

Restore the PSF as a sponsor

---

CODE_OF_CONDUCT.md
_pages/conduct.html

This adds examples of unacceptable behavior and procedures for reporting incidents to the Code of Conduct. These were taken from PyCon's Code of Conduct which is under the [Creative Commons Attribution-ShareAlike 3.0 Unported License](https://creativecommons.org/licenses/by-sa/3.0/).

Code of Conduct Updates

---

_schedule/talks/2023-10-17-07-30-virtual-co-writing.md
_schedule/talks/2023-10-18-07-30-virtual-co-writing.md
_schedule/talks/2023-10-19-07-30-virtual-co-writing.md

2023-10-17-07-30-virtual-co-writing.md

---

_places/boxcar.md
_places/neomonde.md
_places/pure-soul.md

* Fixed a couple of typos
* Fixed restaurant website link

Improve Around Durham section

---

_schedule/talks/2023-10-16-12-00-t1-vue-django-combining-django-templates-and-vue-single-file-components-without-compromise.md

Make the script tag preformatted in Mike's talk

---

_pages/about.html
_pages/covid19.html
_pages/opportunity-grants.md
_pages/tickets.html
_pages/visas.md

* Commented out talk and og submission links on About page
* Updated OG page to indicate that notifications have been sent
* Added get invitation letter link to OG page (maybe link to Visa Support page would be preferable?)
* Consolidated text below ticket table into table (was there a reason to have the text below the table? almost all of the text was exact duplicate of table)
* A few typos/grammar fixes

Fixing small things

---

_schedule/talks/2023-10-16-16-45-t1-working-with-neo4j-with-django-neomodel-library.md

Fixed typo in talk "working-with-neo4j-with-django-neomodel-library" - fixed talk title, path, and slug

Fixed typo in talk working-with-neo4j-with-django-neomodel-library

---

_presenters/andrew-knight.md
_schedule/talks/2023-10-18-09-45-keynote-testing-modern-web-apps-like-a-champion.md

I forgot to run bin/process.py before submitting

🚜 Reformat Andrew's keynote

---

_presenters/drishti-jain.md

Add Drishti Jain's Website

---

_posts/2023-09-12-panel.md
_schedule/talks/2023-10-18-16-50-panel-discussion-who-put-me-in-charge.md

Update post and schedule with Charles' title and editing discussion topics.

Update post and schedule for panel announcement

---

bin/generate_schedule_csv_for_online_platform.py
bin/generate_speaker_csv_for_online_platform.py

These are currently for Loudswarm. They should be flexible for other platforms in the future.

Automate generating CSVs for presenters and the schedule.

---

_pages/trivia.html
_posts/2023-07-07-django-trivia.md
_schedule/talks/2023-10-18-19-00-django-trivia.md

This adds a talk to the schedule for the trivia event (Wed night at 7pm). It also defines the rules and logistics for the event.

Publish trivia rules, details and logistics.

---

_presenters/flavio-juvenal.md

Update flavio-juvenal.md with website

Update flavio-juvenal.md with website

---

_presenters/denny-biasiolli.md

updating speaker's company

---

_presenters/thiago-bellini-ribeiro.md
_schedule/talks/2023-10-17-11-10-t1-building-high-performance-type-safe-graphql-apis-with-strawberry-and-django.md

* Improve "Building high-performance, type-safe GraphQL APIs with Strawberry and Django" talk description
* Add a website for Thiago Bellini Ribeiro

Improve Strabwery Django's talk description

---

_schedule/talks/2023-10-16-15-55-t1-hosting-and-devops-for-django.md

Updates talk description for "Hosting and DevOps for Django"

Updates talk description for "Hosting and DevOps for Django"

---

_presenters/scott-cranfill.md
_schedule/talks/2023-10-18-13-20-t2-best-practices-for-making-a-wagtail-site-as-accessible-as-possible.md

Refining the description of my talk and my bio.

Update talk description and bio for Scott Cranfill

---

_presenters/pavel-sviridov.md

Updated profile info for Pavel Sviridov. Changed the company name following a rebranding.

Update bio for Pavel Sviridov

---

_presenters/ernesto-rico-schmidt.md

Added Website and some additional info about me

Update bio for Ernesto Rico Schmidt

---

static/iframe_compat.js

The FAQ is much more confusing when we don't tell a person that every question's answer is YES.

Don't remove the FAQs sub nav title from the iframe.

---

_pages/trivia.html

Using Google Forms will make processing the answers significantly easier.

Revising Trivia rules

---

_schedule/talks/2023-10-17-20-00-board-game-night.md

📆 Add board game night to the schedule

---

_includes/nav.html

Bring back the "buy tickets" link back to the nav for T-shirt donations

---

_schedule/talks/2023-10-16-11-10-t0-contributing-to-django-or-how-i-learned-to-stop-worrying-and-just-try-to-fix-an-orm-bug.md

Add slides for my presentation Contributing to Django or how I learned to stop worrying and just try to fix an ORM Bug
None

Add slide link for @ryancheley presentation

---

_schedule/talks/2023-10-17-17-15-t1-what-django-deployment-is-really-about.md
_schedule/talks/2023-10-18-10-40-t2-django-migrations-friend-or-foe-optimize-your-django-migrations-for-faster-testing.md

This PR is part of #272 and it add videos for these talks:

:tv: Adds missing youtube_urls
